name: CI

on:
  push:
    branches:
    - '/**'
    - master
  pull_request:
    branches:
    - master

jobs:
  runner-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      redis:
        image: redis
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: user
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn test
        env:
          SPRING_REDIS_HOST: redis
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user
